analyses_directory: analyses
brand: assets/go-performance-quality-brand.png
infographics_directory: infographics
kifu_directory: kifu
plots_directory: plots
renders_directory: renders
transformation_parameters: configuration/hyperparameters2.npy

threads: 8
buffer: 64

katago:
  executable: "C:/Go/KataGo/katago-v1.15.3-cuda12.1-cudnn8.9.7-windows-x64/katago.exe"
  configuration: "C:/Go/KataGo/katago-v1.15.3-cuda12.1-cudnn8.9.7-windows-x64/oracle.cfg"
  model: "C:/Go/KataGo/networks/kata1-b18c384nbt-s9996604416-d4316597426.bin.gz"
  analysis_threads: 128
  search_threads: 1
  max_playouts: 16385  # how many times to expand the root node when analyzing a position
  max_visits: 1048576  # how many times a node may be visited over the course of all positions analyzed

accuracy:
  lead_drop: 0.5
  max_visit_ratio: 0.2
  top_moves: 3
  winrate_drop: 0.005
